# Generated by Django 3.2.6 on 2021-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
