# Generated by Django 3.2.6 on 2021-08-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['updated']},
        ),
    ]
