# Generated by Django 3.2.6 on 2021-08-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated']},
        ),
    ]
