# Generated by Django 3.2.6 on 2021-08-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
